# Generated by Django 3.0.5 on 2021-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pgdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('phoneno', models.CharField(max_length=150)),
                ('pemail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('uid', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=500)),
                ('bhk', models.CharField(max_length=500)),
                ('nopeople', models.CharField(max_length=500)),
                ('vacancies', models.CharField(max_length=500)),
                ('furnished', models.CharField(max_length=150)),
                ('accomodation', models.CharField(max_length=500)),
                ('bachelor', models.CharField(max_length=500)),
                ('ac', models.CharField(max_length=500)),
                ('geyser', models.CharField(max_length=500)),
                ('smoking', models.CharField(max_length=500)),
                ('drink', models.CharField(max_length=500)),
                ('vegnonveg', models.CharField(max_length=500)),
                ('washingmachine', models.CharField(max_length=500)),
            ],
        ),
    ]
